package com.example.f1bets.ui.circuit


import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.Navigation
import com.example.f1bets.R
import com.example.f1bets.databinding.FragmentCreateCircuitsBinding
import com.google.firebase.firestore.FirebaseFirestore


class CreateCircuitsFragment : Fragment() {

    private lateinit var binding: FragmentCreateCircuitsBinding
    private val db = FirebaseFirestore.getInstance()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = FragmentCreateCircuitsBinding.inflate(inflater, container, false)

        binding.btnAddCircuit.setOnClickListener {
            createCircuit()
        }

        return binding.root
    }

    private fun createCircuit() {
        val name = binding.txtNameCircuit.text.toString().trim()
        val country = binding.txtCountry.text.toString().trim()
        val laps = binding.txtLaps.text.toString().toLongOrNull() ?: 0
        val length = binding.txtLegth.text.toString().toLongOrNull() ?: 0
        //val picture = binding.imgCircuit.text.toString().trim()

        // Validate that required fields are not empty
        if (name.isNotEmpty() && country.isNotEmpty() && laps > 0 && length > 0) {
            val newCircuit = hashMapOf(
                "nameCircuit" to name,
                "country" to country,
                "laps" to laps,
                "length" to length,
                //"picture" to picture
            )

            // Add the new circuit to the circuit collection
            db.collection("circuit")
                .add(newCircuit)
                .addOnSuccessListener { documentReference ->
                    // Get the autogenerated id of the circuit and add it into the document
                    val newCircuitId = documentReference.id
                    // Update the new document of the new bet, with the field of its id
                    db.collection("circuit").document(newCircuitId)
                        .update("id", newCircuitId)
                    Navigation.findNavController(requireView()).navigate(R.id.action_createCircuitsFragment_to_nav_Circuits)

                }
                .addOnFailureListener {
                }
        } else {
        }
    }
}